version: '3'
services:
  db:
    container_name: '${CONTAINER_NAME}_db'
    image: '${DB_IMAGE}'
    restart: unless-stopped
    volumes:
      - './db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  wordpress:
    depends_on:
      - db
    container_name: '${CONTAINER_NAME}'
    build:
      context: .
    restart: unless-stopped
    volumes:
      - './html:/var/www/html'
      - './html/wp-content:/var/www/html/wp-content'
    environment:
      WORDPRESS_DB_HOST: '${CONTAINER_NAME}_db:3306'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_TABLE_PREFIX: '${WORDPRESS_TABLE_PREFIX}'
      VIRTUAL_HOST: '${DOMAINS}'
      LETSENCRYPT_HOST: '${DOMAINS}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
networks:
  default:
    external:
      name: '${NETWORK}'
